### ISSUE TITLE
how to modify the connectionist Temporal Classification (CTC) layer of the network to also give us a confidence score?

### ISSUE THREAD

**Issue by vinayakarannil** [wanghaisheng/awesome-ocr#108]
how to modify the connectionist Temporal Classification (CTC) layer of the network to also give us a confidence score?  i am using tensorflows tf.nn.ctc_beam_search_decoder

**Comment by wanghaisheng** [comment]
not a tf guy, but do take a look at these first ,

https://github.com/lingochamp/kaldi-ctc/blob/master/src/lat/confidence.h
https://github.com/MhLiao/TextBoxes/issues/41
https://arxiv.org/pdf/1805.11161.pdf
https://github.com/ChWick/calamari/blob/6a6fd0172d0dcdbf5f9195cdd81db727f12b026e/calamari_ocr/ocr/voting/confidence_voter.py

**Comment by wanghaisheng** [comment]
end how？@vinayakkailas
