### ISSUE TITLE
 【Rosetta：大规模图像文字检测识别系统】《Rosetta: Large scale system for text detection and recognition in images》[Facebook] (2018) O

### ISSUE THREAD

**Issue by wanghaisheng** [wanghaisheng/awesome-ocr#114]
https://dl.acm.org/citation.cfm?id=3219861

**Comment by gsgou** [comment]
https://code.fb.com/ai-research/rosetta-understanding-text-in-images-and-videos-with-machine-learning/

**Comment by wanghaisheng** [comment]
@gsgou  thx  I  have never read a deep analysis article about this one

**Comment by yayagepeide** [comment]
Is there any method to get the source code?

**Comment by wanghaisheng** [comment]
@zhaoyangze 这是不可能的把
