### ISSUE TITLE
2018年末撸串计划

### ISSUE THREAD

**Issue by wanghaisheng** [wanghaisheng/awesome-ocr#121]
2018眼看着收尾了，拟组织一波线下活动，欢迎有兴趣的、打酱油的大家能积极发表意见，形式的话分两个：
>
环节1.在某个场地进行一波自我介绍，一两页PPT形式的业务、方法、成果介绍最佳 

环节2.在1的基础上 组织有进一步沟通的童靴撸个串啥的 进一步加强沟通，增进感情，人多就AA。

按照自己就近城市,选择对应的表情，参与反馈：
*    😄 对环节1有兴趣参加   对环节2有兴趣参加 
*    👎对环节1有兴趣参加   对环节2没兴趣参加
*    👍对环节1没兴趣参加   对环节2有兴趣参加
*    😕 对环节1没有兴趣参加   对环节2没有兴趣参加

**Comment by wanghaisheng** [comment]
深圳分会场
牵头人：wanghaisheng

**Comment by wanghaisheng** [comment]
北京分会场
牵头人：

**Comment by wanghaisheng** [comment]
上海分会场
牵头人：

**Comment by wanghaisheng** [comment]
杭州分会场
牵头人：

**Comment by wanghaisheng** [comment]
南京分会场
牵头人：

**Comment by billyzju** [comment]
@wanghaisheng 麻烦更新一下微信群新的名片OK？之前的过期了。谢谢。
