### ISSUE TITLE
希望可以增加PaddleOCR、AgentOCR

### ISSUE THREAD

**Issue by GT-ZhangAcer** [wanghaisheng/awesome-ocr#124]
您好王老师，今年有两个质量较高的OCR开源项目，想加入到awesome-ocr中，希望可以接受~
## PaddleOCR
[PaddleOCR: PaddlePaddle/PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)
```
超轻量级模型大小低至9.4M，支持80+语言模型，且内置训练模块、半监督标注工具、板面分析模型，中文方面识别占优。
```
## AgentOCR
[AgentOCR: AgentMaker/AgentOCR](https://github.com/AgentMaker/AgentOCR)
```
继承PaddleOCR优势，在此基础上提供了ONNX后端，并额外支持了DirectX加速支持，在Windows部署有显著的兼容性和性能优势。
```

**Comment by wanghaisheng** [comment]
你直接提个pull request 我很快就合并了

**Comment by GT-ZhangAcer** [comment]
已经提交PR了，感谢王老师。
