### ISSUE TITLE
Adnan Ul-Hasan的博士论文-参考文献

### ISSUE THREAD

**Issue by wanghaisheng** [wanghaisheng/awesome-ocr#2]
[ABB13] ABBYY, January 2013. available at ?iiT,ffrrrX##vvX+QKf `2+Q;MBiBQMnb2`p2`.
[AHN+14] Q. U. A. Akram, S. Hussain, A. Niazi, U. Anjum, and F. Irfan. Adpating Tesseract for Complex Scripts: An Example of Urdu Nastalique. In DAS, pages 191–195, 2014.
[Bai92] H. S. Baird. Document Image Defect Models. In H. S. Baird, H. Bunke, andK.Yamamoto,editors,StructuredDocumentImageAnalysis.SpringerVerlag,1992.
[BC09] U. Bhattacharya and B.B. Chaudhuri. Handwritten numeral databases of indian scripts and multistage recognition of mixed numerals. Pattern Analysis and Machine Intelligence, IEEE Transactions on, 31(3):444– 457, 2009.
[BMP02] S. Belongie, J. Malik, and J. Puzicha. Shape Matching and Object RecongitionusingShapeContexts. IEEETransactiononPatternAnalysisand Machine Intelligence,24(4):509–522, April 2002.
[BPSB06] U. Bhattacharya, S.K. Parui, B. Shaw, and K. Bhattacharya. Neural combination of ann and hmm for handwritten devanagari numeral recognition. In ICFHR,2006.
[BR14] A. Belaid and M. I. Razzak. Middel Eastern Character Recognition. In D. Doermann and K. Tombre, editors, Handbook of Document Image Processing and Recognition,pages 427–457. Springer,2014.
[BRB+09] F.Boschetti,M.Romanello,A.Babeu,D.Bamman,andG.Crane. ImprovingOCRAccuracyforClassicalCriticalEditions. InECDL,pages156–167, 2009.
[Bre01] T. M. Breuel. Segmentation of Hand-printed Letter Strings using a Dynamic Programming Algorithm. In ICDAR, pages 821–826, sep 2001.

Bibliography 148
[Bre08] T.M.Breuel. TheOCRopusOpenSourceOCRSystem. InB.A.Yanikoglu andK.Berkner,editors,DRR-XV,page68150F,SanJose,USA,Jan2008.
[BS08] T.M.BreuelandF.Shafait. AutoMLP:Simple,Effective,FullyAutomated Learning Rate and Size Adjustment. In The Learning Workshop, January 2008.
[BSB11] S.S.Bukhari,F.Shafait,andT.M.Breuel. HighPerformanceLayoutAnalysis of Arabic and Urdu Document Images. In ICDAR, page 1275–1279, Bejing, China, sep 2011.
[BSF94] Y.Bengio,P.Simard,andP.Frasconi. LearningLong-TermDependencies withGradientDescentisDifficult. IEEETransactionsonNeuralNetworks, 5(2):157–166, 1994.
[BT14] H. S. Baird and K. Tombre. The Evolution of Document Image Analysis. In D. Doermann and K. Tombre, editors, Handbook of Document Image Processing and Recognition, pages 63–71. Springer,2014.
[BUHAAS13] T.M.Breuel,A.Ul-Hasan,M.AlAzawi,andF.Shafait. HighPerformance OCR for Printed English and Fraktur using LSTM Networks. In ICDAR, WashingtonD.C. USA, aug 2013.
[CL96] R.G.CaseyandE.Lecolinet. ASurveyofMethodsandStrategiesinCharacterSegmentation. IEEETrans.PatternAnalysisandMachineIntelligence, 18(7):690–706, 1996.
[CP95] B.B. Chadhuri and S. Palit. A feature-based scheme for the machine recognitionof printedDevanagari Script. 1995.
[CP97] B.B. Chaudhuri and U. Pal. An OCR system to read two Indian language scripts: Bangla and Devnagari (Hindi). In Document Analysis and Recognition, 1997., Proceedings of the Fourth International Conference on, volume 2, pages 1011–1015. IEEE, 1997.
[Eik93] L. Eikvil. OCR – Optical Characer Recognition. Technicalreport, 1993.
[EM08] M. S. M. El-Mahallway. A Large Scale HMM-Based Omni Font-Written OCR System For Cursive Scripts. PhD thesis, Cairo, Egypt, 2008.
[ERA57] ERA. An Electronic Reading Automation. Electronics Engineering, pages 189–190, 1957.
[ESB14] A.F.Echi,A.Saidani, and A.Belaid. HowtoseparatebetweenMachinePrinted/HandwrittenandArabic/LatinWords? ElectronicLettersonComputer Vision and Image Analysis,13(1):1–16, 2014.
Bibliography BIBLIOGRAPHY
[Fuc] M. Fuchs. The Use of Gothic OCR in processing Historical Documents. Technicalreport.
[Fuk80] K. Fukushima. Ncocognitron: A Self-Organizing Neural Network Model foraMechanismofPatternRecognitionUnaffectedbyShiftinPosition. Biological Cybernetics, 36:193–202, 1980.
[FV11] L.FurrerandM.Volk. ReducingOCRerrorsinGothicscriptdocuments. In Workshop on Language Technologies for Digital Humanities and Cultural Heritage,page 97–103, Hissar,Bulgaria, September2011.
[GAA+99] N. Gorski, V. Anisimov, E. Augustin, O. Baret, D. Price, and J.-C. Simon. A2iA Check Reader: A Family of Bank Check Recognition Systems. In ICDAR,pages 523–526, Sep 1999.
[Gat14] B. G. Gatos. Image Techniques in Document Analysis Process. In D. DoermannandK.Tombre,editors,HandbookofDocumentImageProcessing and Recognition,pages 73–131. Springer,2014.
[GDS10] D.Ghosh,T.Dube,andA.P.Shivaprasad. ScriptRecognition-AReview. IEEE Trans. Pattern Analysis and Machine Intelligence, 32(12):2142–2161, 2010.
[GEBS04] A. Graves, D. Eck, N. Beringer, and J. Schmidhuber. Biologically Plausible Speech Recognition with LSTM Neural Nets. In Auke Jan Ijspeert, Masayuki Murata, and Naoki Wakamiya, editors, BioADIT, volume 3141 of Lecture Notes in Computer Science,page 127–136. Springer,2004.
[GFGS06] A. Graves, S. Fernández, F. J. Gomez, and J. Schmidhuber. ConnectionistTemporalclassification: LabellingUnsegmentedSequenceDatawith Recurrent Neural Networks. In ICML,page 369–376, 2006.
[GLF+08] A.Graves,M.Liwicki,S.Fernandez,H.BunkeBertolami,andJ.Schmidhuber. Anovelconnectionistsystemforunconstrainedhandwritingrecognition. IEEETrans.onPatternAnalysisandMachineIntelligence,31(5):855– 868, May2008.
[GLS11] B. Gatos, G. Louloudis, and N. Stamatopoulos. Greek Polytonic OCR basedonEfficientCharacterClassNumbverReduction. InICDAR,pages 1155–1159, Bejing, China, aug 2011.
[GPTF13] D.Genzel,A.C.Popat,R.Teunen,andY.Fujii. HMM-basedScriptIdentification for OCR. In International Workshop on Multilingual OCR, page 2, WashingtonD.C., USA., August2013.
[Gra] A. Graves. RNNLIB: A recurrent neural network library for sequence learning problems. ?iiT,ffbQm`+27Q`;2XM2ifT`QD2+ibf`MMHf.
[Gra12] A. Graves. Supervised Sequence Labelling with Recurrent Neural Networks, volume385 of Studies in Computational Intelligence. Springer,2012.
[GS05] A. Graves and J. Schmidhuber. Framewise Phoneme Classification with Bidirectional LSTM Networks. In IJCNN, pages 2047–2052, Montreal, Canada, 2005.
[GS08] A. Graves and J. Schmidhuber. Offline Handwriting Recognition with Multidimensional Recurrent Neural Networks. In Daphne Koller, Dale Schuurmans,YoshuaBengio,andLéonBottou,editors,NIPS,page545– 552. CurranAssociates,Inc., 2008.
[GSL+] B. Gatos, N. Stamtopoulos, G. Louloudis, G. Sfikas, G. Retsinas, V. Papavassiliou, F. Simistira, and V. Katsouros. GROPLY-DB: An Old Greek PolytonicDocumentsImageDatabase. InICDAR,pages646–650,Nancy, France,August.
[Han62] W. J. Hannan. R. C. A. Multifont Reading Machine. Optical Character Recognition, pages 3–14, 1962.
[HBFS01] S.Hochreiter,Y.Bengio, P.Frasconi,andJ.Schmidhuber. GradientFlow inRecurrentNets: TheDifficultyofLearningLong-TermDependencies. In S. C. Kremer and J. F. Kolen, editors, A Field Guide to Dynammical Recurrent Neural Networks.IEEE Press, 2001.
[HHK08] Md. A. Hasnat, S. M. M. Habib, and M. Khan. A High Performance Domain Specific OCR for Bangla Script. In T. Sobh, editor, Novel Algorithms and Techniques in Telecommunication, Automation and Industrial Electronics, page 174–178. Springer,2008.
[HS97] S. Hochreiter and J. Schmidhuber. Long Short-Term Memory. Neural Computation, 9(8):1735–1780, 1997.
[HW65] D. H. Hubel and T. N. Wiesel. Receptive Fields and Functional ArchitectureinTwoNonstriateVisualAra(18and19)oftheCat. JournalofNeurophysiology,28:229–289, 1965.
[IH07] M.IjazandS.Hussain. CorpusBasedUrduLexiconDevelopment. InCLT, Peshawar,Pakistan,2007.
[III14] IIIT,June 2014. ?iiT,ffHi`+XBBBiX+XBMf+Q`Tmbf+Q`TmbX?iKH.

[IOK63] T.Iijima,Y.Okumura,andK.Kuwabara.NewProcessofCharacterRecognition using Sieving Method. Information and Control Research, 1(1):30– 35, 1963.
[JBB+95] L. Jackel, M. Battista, H. Baird, J. Ben, J. Bromley, C. Burges, E. Cosatto, J. Denker, H. Graf, H. Katseff, Y. Le-Cun, C. Nohl, E. Sackinger, J. Shamilian, T. Shoemaker, C. Stenard, I. Strom, R. Ting, T. Wood, and C. Zuraw. Neural-Net Applications in Character Recognition and Document Analysis. Technicalreport, 1995.
[JDM00] A.K. Jain, R. P W Duin, and Jianchang Mao. Statistical pattern recognition: areview. PatternAnalysisandMachineIntelligence,IEEETransactions on,22(1):4–37, Jan 2000.
[JKK03] C.V. Jawahar, M.N.S.S.K. Kumar, and S.S.R. Kiran. A Bilingual OCR for Hindi-TeluguDocumentsanditsApplications. InICDAR,volume3,pages 408–412, 2003.
[KC94] G. E. Kopec and P. A. Chou. Document Image Decoding using Markov Source Models. IEEE Transaction on Pattern Analysis and Machine Intelligence,16(6):602 – 617, 1994.
[KH99] T.KanungoandR.M.Haralick. AnAuotmaticClosed-LoopMethodology for Generating Character Groundtruth for Scanned Documents. IEEE Trans. on Pattern Analysis and Machine Intellignece,21(2):179–183, 1999.
[KK02] D.-W. Kim and T. Kanungo. Attributed Point Matching for Automatic Groundtruth Generation. Int. Journal on Document Analysis and Recognition, 5(1):47–66, 2002.
[KNSG05] S. Kompalli, Sankalp Nayak, S. Setlur, and V. Govindaraju. Challenges in OCR of Devanagari Documents. In ICDAR, pages 327–331 Vol. 1, Seol, Korea,Aug2005.
[KRM+05] T. Kanungo, P. Resnik, S. Mao, D. W. Kim, and Q. Zheng. The Bible and Multilingual Optical Character Recognition. Communication of the ACM, 48(6):124–130, Jun 2005.
[KSKD15] I. U. Khattak, I. Siddiqui, S. Khalid, and C. Djeddi. Recognition of Urdu Ligatures - A Holistic Approach . In ICADR,Nancy, France,aug 2015.
[KUHB15] T.Karayil,A.Ul-Hasan,andT.M.Breuel. ASegmentation-FreeApproach for Printed Devanagari Script Recognition. In ICDAR, pages 946–950, Nancy, France,aug 2015.
Bibliography 152
[LBK+98] Z.A.Lu,I.Bazzi,A.Kornai,J.Makhoul,P.S.Natarajan,andR.Schawartz. A Robust, Language-Independent OCR System. In AIPR Workshop: Advancement in Computer-Assisted Recognition,pages 96–104, 1998.
[LC89] Y. Le-Cun. Generalization and Network Desgin Strategies. Connectionisms in Perspective,Jun 1989.
[LRHP97] J. Liang, R. Rogers, R. M. Haralick, and I.T. Philips. UW-ISL Document Image Analysis Toolbox: An Experimental Environment. In ICDAR, page 984–988, Ulm, Germany,aug 1997.
[LSN+99] Z.Lu,R.M.Schwartz,P.Natarajan,I.Bazzi,andJ.Makhoul. Advancesin BBN BYBLOSOCR System. In ICDAR, pages 337–340, 1999.
[Lu95] Y.Lu. MachinePrintedCharacterSegmentation—AnOverview. Pattern Recognition, 28(1):67 – 80, 1995.
[MAM+08] S. Mozaffari, H. Abed, V. Märgner, K. Faez, and A. Amirshahi. IfN/FarsiDatabase: A Database of Farsi Handwritten City Names. In ICFHR, page 397–402, Montreal, Canada, aug 2008.
[Mat15] J. Matas. Efficient character skew rectification in scene text images. In ACCV,volume9009, page 134. Springer,2015.
[MGS05] S. Marinai, M. Gori, and G. Soda. Artificial Neural Networks for Document Analysis and Recognition. IEEE Trans. on Pattern Analysis and Machine Intellignece,27(1):23–35, January 2005.
[MSLB98] J. Makhoul, R. Schwartz, C. Lapre, and I. Bazzi. A Script-Independent Methodology for Optical Character Recognition. Pattern Recognition, 31(9):1285 – 1294, 1998.
[MSY92] S. Mori, C. Suen, and K. Yamamoto. Historical Review of OCR Research and Development. IEEE, 80(7):1029–1058, 1992.
[MWW13] Y. Mei, X. Wang, and J. Wang. An Efficient Character Segmentation Algorithm for Printed Chinese Documentation. In UCMA, pages 183–189, 2013.
[Nag92] G. Nagy. At the Frontiersof OCR. IEEE, 80(7):1093–1100, 1992.
[NHR+13] S. Naz, K. Hayat, M.I. Razzak, M.W. Anwar, S.A. Madani, and S.U. Khan. The Optical Character Recognition of Urdu-like Cursive Scripts. Pattern Recognition, 47(3):1229–1248, 2013.
Bibliography BIBLIOGRAPHY
[NHR+14] S. Naz, K. Hayat, M.I. Razzak, M.W. Anwar, S.A. Madani, and S.U. Khan. Challenges in Baseline Detection of Arabic Script Based Languages, 2014.
[NLS+01] P.Natarajan,Z.Lu,R.M.Schwartz,I.Bazzi,andJ.Makhoul. Multilingual Machine Printed OCR. International Journal on Pattern Recognition and Artificial Intelligence,15(1):43–63, 2001.
[NS14] N. Nobile and Y. Suen. Text Segmentation for Document Recognition. In D. Doermann and K. Tombre, editors, Handbook of Document Image Processing and Recognition, pages 257–290. Springer,2014.
[NUA+15] S. Naz, A. I. Umar, R. Ahmad, S. B. Ahmed, S. H. Shirazi, and M.I. Razzak. Urdu Nastaĺiq Text Recognition System Based on Multidimensional Recurrent Neural Network and Statistical Features. Neural Computing and Applications, 26(8), 2015.

[OCR15] OCRopus, January 2015. available at ?iiTb,ff;Bi?m#X+QKfiK#/2pf Q+`QTv.

[OHBA11] M. A. Obaida, M. J. Hossain, M. Begum, and M. S. Alam. Multilingual OCR(MOCR):AnApproachtoClassifyWordstoLanguages. Int’lJournal of Computer Applications, 32(1):46–53, October2011.

[Pal04] U. Pal. Indian Script Character Recognition: A Survey. Pattern Recognition, 37:1887–1899, 2004.
[PC97] U.PalandB.B.Chaudhuri. PrintedDevanagariscriptOCRsystem. VIVEKBOMBAY-,10:12–24, 1997.
[PC02] U. Pal and B. B. Chaudhuri. Identification of different script lines from multi-script documents. Image Vision Computing, 20(13-14):945–954, 2002.
[PD14] U. Pal and N. S. Dash. Script Identification. In D. Doermann and K. Tombre, editors, Handbook of Document Image Processing and Recognition, pages 291–330. Springer,2014.
[PMM+02] M. Pechwitz, S.S. Maddouri, V. Märgner, N. Ellouze, and H. Amiri. IfN/ENIT-Database of Handwritten Arabic Words. In CIFED, page 129– 136, Hammamet, Tunisia,oct 2002.
[Pop12] A. C. Popat. Multilingual OCR Challenges in Google Books, 2012.
Bibliography 154
[PS05] U. Pal and A. Sarkar. Recognition of Printed Urdu Text. In ICDAR, pages 1183–1187, 2005.
[PV10] M. C. Padma and P. A. Vijaya. Global Approach For Script Identification UsingWaveletPacketBasedFeatures. InternationalJournalofSignalProcessing, Image Processing And Pattern Recognition,3(3):29–40, 2010.
[Rab89] L. R. Rabiner. A Tutorial on Hidden Markov Models and Selected Applications in Speech Recognition. Proceedings of the IEEE, 77(2):257–286, 1989.
[Ras10] Rashid,S.F.andShafait,F.andBreuel,T.M. DiscriminativeLearningFor Script Recognition. In ICIP,Hong Kong,sep 2010.
[Ras14] S. F. Rashid. Optical Character Recognition – A Combined ANN/HMM Approach. PhD thesis, Kaiserslautern,Germany,2014.
[RDL13] R. Rani, R. Dhir, and G. S. Lehal. Script Identification of Pre-segmented Multi-font Characters and Digits. In ICDAR, Washington D.C., USA, August 2013.
[RH89] W.S.RosenbaumandJ.J.Hilliard. SystemandMethodforDeferredProcessing of OCR Scanned Mail, 07 1989.
[SAL09] R. Smith, D. Antonova, and D. S. Lee. Adapting the Tesseract Open Source OCR Engine for Multilingual OCR. In Int. Workshop on Multilingual OCR, July 2009.
[SCPB13] N.Sharma,S.Chanda,U.Pal,andM.Blumenstein.Word-wisescriptidentificationfromvideoframes. InICDAR,pages867–871,WashingtonD.C. USA, Aug2013.
[Sen94] A.W.Senior. OfflineCursiveHandwritingRecognitionusingRecurrentNeural Networks. PhD thesis, England, 1994.
[SHNS09] M. Sagheer, C. He, N. Nobile, and C. Suen. A New Large Urdu Database for Off-Line Handwriting Recognition. page 538–546, Vietri sul Mare, Italy, sep 2009.
[SIK+09] F. Slimane, R. Ingold, S. Kanoun, A. M. Alimi, and J. Hennebert. A New ArabicPrintedTextImageDatabaseandEvaluationProtocols. InICDAR, page 946–950, Barcelona, Spain, July 2009.
[SJ12] N. Sankaran and C.V. Jawahar. Recognition of printed Devanagari text using BLSTM Neural Network. In ICPR,pages 322–325, nov2012.
Bibliography BIBLIOGRAPHY
[SJ15] A.K.SinghandC.V.Jawahar. CanRNNsReliablySeparateScriptandLanguageatWordandLineLevel? InICDAR,pages976–980,Nancy,France, August2015.
[SKB08] F. Shafait, D. Keysers, and T. M. Breuel. Efficient Implementation of Local Adaptive Thresholding Techniques Using Integral Images. In B. A. YanikogluandK.Berkner,editors,DRR-XV,page681510,SanJose,USA, Jan 2008.
[SLMZ96] R. Schwartz, C. LaPre, J. Makhoul, and Y. Zhao. Language-Independent OCRUsingaContinuousSpeechRecognitionSystem. InICPR,page99– 103, Vienna, aug 1996.
[SM73] R. Sinha and K. Mahesh. A Syntactic Pattern Analysis System and Its Application toDevanagari Script Recognition. 1973.
[Smi07] R. Smith. An Overview of the Tesseract OCR Engine. In ICDAR, pages 629–633, 2007.
[Smi13] R.Smith. HistoryoftheTesseractOCREngine: WhatWorkedandWhat Didnt￿. In DRR-XX,San Franciso,USA, Feb2013.
[SP00] J. Sauvola and M. Pietikäinen. Adpative Document Image Binarization. Pattern Recognition, 33:225–236, 2000.
[Spi97] A. L. Spitz. Multilingual Document Recognition. In H. Bunke and P. S. P. Wang, editors, Handbook of character Recognition and Document Image Analysis, pages 259–284. WorldScientific Publishing Company,1997.
[SPS08] B. Shaw, K.S. Parui, and . Shridhar. Offline Handwritten Devanagari Word Recognition: A holistic approach based on directional chain code feature and HMM. In ICIT,pages 203–208. IEEE, 2008.
[SS13] N.SabbourandF.Shafait. ASegmentation-FreeApproachtoArabicand Urdu OCR. In DRR-XX,San Francisco,CA, USA, feb 2013.
[SSR10] T.Saba,G.Sulong,andA.Rehman. ASurveyonMethodsandStrategies onTouchedCharactersSegmentation. InternationalJournalofResearch and Reviews in Computer Science,1(2):103–114, 2010.
[SUHKB06] F. Shafait, A. Ul-Hasan, D. Keysers, and T.M. Breuel. Layout analysis of urdu document images. In Multitopic Conference, 2006. INMIC ’06. IEEE, pages 293–298, Dec 2006.
Bibliography 156
[SUHP+15] F. Simistira, A. Ul-Hasan, V. Papavassiliou, B. Gatos, V. Katsouros, and M.Liwicki. RecognitionofHistoricalGreekPolytonicScriptsUsingLSTM Networks. In ICDAR,page 766–770, Nancy, France,aug 2015.
[Sut12] I. Sutskever. Training Recurrent Neural Networks. PhD thesis, Dept. of ComputerScience, Univ.of Toronto,2012.
[SYVY10] R. Singh, C.S. Yadav, P. Verma, and V. Yadav. Optical Character Recognition(OCR)forPrintedDevnagariScriptUsingArtificialNeuralNetwork. International Journal of Computer Science & Communication, 1(1):91–95, 2010.
[Tau29] G. Tauscheck. Reading machine, 12 1929.
[Tes14] Tesseract, June 2014. ?iiT,ff+Q/2X;QQ;H2X+QKfTfi2bb2`+i@Q+`f.
[TNBC00] K.Taghva,T.Nartker,J.Borsack,andA.Condit. UNLV-ISRIdocumentcollection for research in OCR and information retrieval. In DRR–VII, page 157–164, San Jose CA, USA, 2000.
[UHAS+15] A. Ul-Hasan, M. Z. Afzal, F. Shafait, M. Liwicki, and T. M. Breuel. A Sequence Learning Approach for Mutliple Script Identification. In ICDAR, pages 1046–1050, Nancy, France,2015.
[UHASB13] A. Ul-Hasan, S. B. Ahmed, F. Shafait, and T. M. Breuel. Offline Printed Urdu Nastaleeq Script Recognition with Bidirectional LSTM Networks. In ICDAR, pages 1061–1065, WashingtonD.C., USA., Aug2013.
[UHB13] A.Ul-HasanandT.M.Breuel. CanweBuildLanguageIndependentOCR using LSTM Networks? In International Workshop on Multilingual OCR, page 9, WashingtonD.C., USA., Aug2013.
[USHA14] S. Urooj, S. Shams, S. Hussain, and F. Adeeba. CLE Urdu Digest Corpus. In CLT,Karachi, Pakistan,2014.
[vBSB08] J. van Beusekom, F. Shafait, and T. M. Breuel. Automated OCR Ground TruthGeneration. In DAS, page 111–117, Nara, Japan, sep 2008.
[VGSP08] G.Vamvakas,B.Gatos,N.Stamatopoulos,andS.Perantonis.AComplete Optical Character Recognition Methodology for Historical Documents. In DAS,page 525–532, Nara, Japan, sep 2008.
[Vit67] A.J. Viterbi. Error bounds for Convolutional Codes and an Asymptotically Optimum Decoding Algorithm. Information Theory, IEEE Transactions on, 13(2):260–269, April 1967.
Bibliography BIBLIOGRAPHY
[Wer90] P. Werbos. Backpropagation Through Time: What Does It Do and How toDo It. In Proceedings of IEEE, volume78, page 1550–1560, 1990.
[Whi13] N. White. Training Tesseract for Ancient Greek OCR. Eutypon, pages 1–11, 2013.
[WLS10] N. Wang, L. Lam, and C. Y. Suen. Noise Tolerant Script Identification of Printed Oriental and English Documents Using a Downgraded Pixel Density Feature. In ICPR, pages 2037–2040, 2010.
[YSBS15] M.RYousefi,M.R.Soheili,T.M.Breuel,andD.Stricker. AComparisonof 1D and 2D LSTM Architectures for Recognition of Handwritten Arabic (Acceptedfor publication). In DRR–XXI, San Francisco,USA, 2015.
[YY94] S.J. Young and S. Young. The HTK Hidden Markov Model Toolkit: Design and Philosophy. Entropic Cambridge Research Laboratory, Ltd., 2:2– 44, 1994.

**Comment by redvipar** [comment]
Hi
Working on a project using entropy algorithm to enhance handwriting can you help

**Comment by wanghaisheng** [comment]
@redvipar  can u share a little more detail

**Comment by redvipar** [comment]
The algorithm is to correct skew and slantness in handwriting to achieve a better recognition

**Comment by wanghaisheng** [comment]
how  can i help u

**Comment by redvipar** [comment]
I need a working code to convert GrayscaleImage to binary image
Can you send me your email and I will send you my work. Code in java

**Comment by wanghaisheng** [comment]
you can touch me wanghaisheng@clearofchina.com
