### ISSUE TITLE
 Chinese/English mixed Character Segmentation as Semantic Segmentation

### ISSUE THREAD

**Issue by wanghaisheng** [wanghaisheng/awesome-ocr#21]
Chinese/English mixed Character Segmentation as Semantic Segmentation
论文：https://arxiv.org/abs/1611.01982
代码

**Comment by wanghaisheng** [comment]
## 摘要

对于多语言的打印体文本来说 OCR任务中字符切分是非常困难的。之前大部分方法只是针对某种单一的语言，本文尝试多语种的文本。这里将中英文混合的情况视为一个语义分割的问题。使用了语义分割领域名为FCN 全卷积网络的架构。FCN无需传统的特征工程，可以自动学习有用的特征

> ```
> OCR character segmentation for multilingual printed documents is difficult due to the diversity of different linguistic characters. Previous approaches mainly focus on monolingual text and are not suitable for multi-lingual cases. In this work, we particularly tackle the Chinese/English mixed case by reframing it as a semantic segmentation problem. We take advantage of the successful architecture called fully convolutional networks (FCN) in the field of semantic segmentation. As a deep architecture, FCN can automatically learn useful features without traditional feature engineering. Given wide enough receptive field, it can utilize the necessary context around a position to better determinate whether this is a splitting point or not. Trained on synthesized samples with simulated random disturbances, FCN can effectively split characters without any hand-crafted features. The experimental results show that our model significantly outperforms the previous methods. It is able to generalize from simulated disturbances to real-world disturbances, generalize from one text content style to another, generalize from seen font styles to unseen ones, and correctly handle disconnected structures and touching characters. 
> ```
1. [用于语义分割的全卷积网络](https://zhuanlan.zhihu.com/p/22280115)
   > 本文译自UC Berkeley的Jonathan Long、Evan Shelhamer、Trevor Darrell的《Fully Convolutional Networks for Semantic Segmentation》，2015 CVPR best paper。
2. https://github.com/shelhamer/fcn.berkeleyvision.org
3. [ Tensorflow implementation of Fully Convolutional Networks for Semantic Segmentation (http://fcn.berkeleyvision.org) ](https://github.com/shekkizh/FCN.tensorflow)
4. [ Fully Convolutional Networks for Semantic Segmentation ](https://github.com/dmancevo/semantic_segmentation) 
5. []()

**Comment by kli017** [comment]
最近在做字符切割，看到这篇文章。对全卷积语义分割还不是很了解不知道有没有相关代码可以学习？

**Comment by wanghaisheng** [comment]
@kli017  暂时也没有找到比较好的代码
