### ISSUE TITLE
寻人启事

### ISSUE THREAD

**Issue by wanghaisheng** [wanghaisheng/awesome-ocr#26]
歡迎對醫療圖像數據處理感興趣的  有那麽一招半式玩的比較溜的小夥伴一起玩耍
主要是兩個方向：
1.歷史文檔的OCR
2.醫療設備中獲取圖像的理解
实习全职均可
edwin_uestc@163.com

**Comment by xlight** [comment]
我老婆是个医生，然而时间真的不太多
