### ISSUE TITLE
关于生成文本行数据的问题

### ISSUE THREAD

**Issue by xiaomaxiao** [wanghaisheng/awesome-ocr#53]
楼主，你用于生成文本行的语料库是随机生成的汉字吗？
还是自己搜集的？
因为有3000多个汉字+标点字母。 如果要自己搜集，如何保证样本的均衡？

**Comment by wanghaisheng** [comment]
我是直接简单粗暴  6000个字每个字出现一次 
每行20个字   单纯依赖每行对应图片的个数来做的 
我觉得你可以使用tesseract 训练中文模型时用的文本  他应该是你想要效果

**Comment by xylcbd** [comment]
有什么关于中文文字图像（单字、单行、单页）生成的开源库吗？

**Comment by xiaomaxiao** [comment]
@wanghaisheng  LSTM 应该是需要大量样本 才会收敛，  6000个 每个出现一次， 训练 不会收敛吧。

用tesseract 训练中文模型时用的文本在哪里

**Comment by xiaomaxiao** [comment]
@xylcbd https://github.com/tmbdev/ocropy/blob/master/ocropus-linegen 参考这个代码。

**Comment by wanghaisheng** [comment]
@xiaomaxiao https://github.com/tesseract-ocr/langdata/blob/master/chi_sim/chi_sim.training_text
你可以看下这个

我说的是假设训练10个字 其中只是一行
xxxxxxxxxxx
那么我生成的图片经过argumenation 这一行会有200个图片

**Comment by xiaomaxiao** [comment]
@wanghaisheng  哇偶，所以是随机汉字 ， +多种字体、噪声 来加大了样本量。
最后效果如何？

chi_sim.training_text 是tesseract 3.0的 original trainfile。

**Comment by wanghaisheng** [comment]
@xiaomaxiao   我 了解新的4.0 lstm的模型也是基于这个文件来的

**Comment by xiaomaxiao** [comment]
https://github.com/tesseract-ocr/langdata/issues/35#issuecomment-320330996

**Comment by wanghaisheng** [comment]
@xiaomaxiao  没太看懂这些个comment

**Comment by xiaomaxiao** [comment]
@ @wanghaisheng  这个comment说 langdata还未更新到4.0

**Comment by xiaomaxiao** [comment]
@wanghaisheng 用CRNN实验了英文，随机组合字母 没有 英文单词效果好。
你用的随机汉字效果如何？

**Comment by wanghaisheng** [comment]
@xiaomaxiao 我们测试了 200汉字 500汉字 效果是很不错的

**Comment by xiaomaxiao** [comment]
@wanghaisheng  可否分享下数据增广的细节？除了用不同字体，还需要写什么方法？argumenation 个图片？

**Comment by wanghaisheng** [comment]
@xiaomaxiao 200个字  每行随机20个 总共用了3000多张图片 
其他增广的方式可以参考https://github.com/szad670401/OCR_CharGen
https://github.com/CatWang/OCR-Picture-Generators

**Comment by xiaomaxiao** [comment]
@wanghaisheng  二值化的样本？不是灰度的吗

**Comment by wanghaisheng** [comment]
@xiaomaxiao 没get到你的点

**Comment by xiaomaxiao** [comment]
@wanghaisheng  因为我做的 文档识别，都是白底黑字，你做的样本 最终二值化了吗？还是直接以灰度传进去的？

**Comment by wanghaisheng** [comment]
@xiaomaxiao 有二值化

**Comment by xiaomaxiao** [comment]
@wanghaisheng  

200个字 每行随机20个 总共用了3000多张图片

我实验了你说的方法，存在严重的过拟合，且没有泛化能力。

**Comment by wanghaisheng** [comment]
@xiaomaxiao 
扩大每种随机的图片数量 如果是30000张 会不会降低过拟合的程度

那个日本人  3000多个字符 训练数据在这里  说的是迭代15万次收敛   但我也没有重现出来  

https://github.com/isaomatsunami/clstm-Japanese/tree/master/testdata3877/mincho

**Comment by xiaomaxiao** [comment]
@wanghaisheng 应该不行

你测试的200汉字 是怎么做的？
