### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by kmustriver** [wanghaisheng/awesome-ocr#68]
您好，我在训练中时候文库的时候出现如下问题：
TRU: u'\u8a13\u8a0a\u905c\u8fc5\u58d3\u62bc\u9d09\u9d28\u5440\u4e2b\u82bd\u7259\u869c\u5d16\u8859\u6daf\u96c5\u555e\u4e9e\u8a1d\u7109\u54bd\u95b9\u7159\u6df9\u9e7d\u56b4\u7814\u8712\u5ca9\u5ef6\u8a00\u9854\u95bb\u708e\u6cbf\u5944\u63a9\u773c\u884d'
   ALN: ''
   OUT: u'\xae'
但是我的gt.txt里面以及生成的图片正常的，请问这要怎么办呢

**Comment by wanghaisheng** [comment]
gt.txt 重新utf8编码保存试试呢

**Comment by kmustriver** [comment]
这样也不行，最后是在命令里指定charset就行了，非常感谢您的回复

**Comment by wanghaisheng** [comment]
@kmustriver 多多探讨 我准备起个微信群
